### ISSUE TITLE
询问参数

### ISSUE THREAD

**Issue by Qu1n-22** [Maxpa1n/gcplm-kgc#1]
您好 
![image](https://github.com/Maxpa1n/gcplm-kgc/assets/58621926/1cf2b130-86a6-483e-af38-65c240e23e66)
这个sh文件中的最后一个参数的77777777是什么作用？
以及，我在删除这个参数后，遇到了
If you want to use `XLMRobertaLMHeadModel` as a standalone, add `is_decoder=True.`
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embedding dimension will be 250006. This might induce some performance reduction as *Tensor Cores* will not be available. For more details about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
这个问题，似乎导致了
![image](https://github.com/Maxpa1n/gcplm-kgc/assets/58621926/1bc44217-2c8f-4677-8a32-c41dff66f1ff)
感谢！
[过程.txt](https://github.com/Maxpa1n/gcplm-kgc/files/12647428/default.txt)

**Comment by Maxpa1n** [comment]
This problem is caused by the update of the transformers library. The version I use is as follows
tokenizers              0.10.3
torch                   1.10.0+cu113
torchaudio              0.10.0+cu113
torchvision             0.11.1+cu113
transformers            4.13.0
