### ISSUE TITLE
entities.txt and filterd.txt missing

### ISSUE THREAD

**Issue by zhaoyi-hb** [Maxpa1n/gcplm-kgc#2]
Thanks for your excellent work, when I run _link_prediciton.py_, the program seems likes lack _entities.txt_ and _filterd.txt_, could you provide the two files?

**Comment by Maxpa1n** [comment]
You can find them here.
https://github.com/luka-group/prix-lm

**Comment by zhaoyi-hb** [comment]
Thanks.
